Repository Somesh-Dahatonde/My-First-Landing-Page, pull requests merged in 2022-10, with the labels that each got.

#1 Added New Fonts
  .vscode/settings.json
  Style.css
  index.html
Labels: bug, enhancement, good first issue, hacktoberfest, hacktoberfest-accepted

#2 Added JOIN US Button
  Style.css
  index.html
Labels: enhancement, good first issue, hacktoberfest, hacktoberfest-accepted

#5 join us page created
  Style.css
  css/join.css
  index.html
  join-us.html
Labels: enhancement, hacktoberfest, hacktoberfest-accepted
